command_project/authapp/urls.py
from django.urls import path
from .views import UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, UserLoginView
from django.contrib.auth.views import LogoutView


app_name = 'auth'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('reg/', UserCreateView.as_view(), name='users_create'),
    path('edit/', UserUpdateView.as_view(), name='users_update'),
    path('remove/', UserDeleteView.as_view(), name='users_remove'),
]

command_project/habr/urls.py
# """habr URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('moderation.urls', namespace='mod')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('django.contrib.auth.urls')),
    path('search/', include('searchapp.urls', namespace='search')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

command_project/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp
from .views import ArticlesView, ArticleView, ArticleCreateView, \
    ArticleUpdateView, ArticlePublishView, ArticleDeleteView, LikeSwitcher


app_name = 'mainapp'

urlpatterns = [
    path('', ArticlesView.as_view(), name='articles'),
    path('category/<int:pk>/', ArticlesView.as_view(), name='category'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article'),
    path('article/create/', ArticleCreateView.as_view(), name='create_article'),
    path('article/delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_article'),
    path('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='update_article'),
    path('article/publish/<int:pk>/', ArticlePublishView.as_view(), name='publish_article'),
    path('about_us/', mainapp.about_us, name='about_us'),
    path('article/<int:article_pk>/comment/reply/<int:pk>', mainapp.CommentReplyView.as_view(), name='comment-reply'),
    path('article/<int:pk>/comment/', mainapp.CommentView.as_view(), name='comment'),
    path('like/<str:model>/<int:pk>', LikeSwitcher.as_view(), name='like'),
    path('help/', mainapp.help, name='help'),
]

command_project/moderation/urls.py
from django.urls import path
from .views import change_moderator_status, ModeratorPage, Ban, Unban

app_name = 'moderation'


urlpatterns = [
    path('moderator_page', ModeratorPage.as_view(), name='moderator_page'),
    path('change_moderator_status/<int:pk>/', change_moderator_status, name='change_moderator_status'),
    path('ban/<str:model>/<int:pk>', Ban.as_view(), name='ban'),
    path('unban/<str:model>/<int:pk>', Unban.as_view(), name='unban'),
               ]

command_project/mainapp/models.py
from django.db import models
from django.utils import timezone

from authapp.models import User
from django.db.models import Q

from mainapp.mixins import ModelClassNameMixin


class ArticleCategoryManager(models.Manager):
    use_for_related_fields = True

    def search(self, query=None):
        qs = self.get_queryset()
        if query:
            query = query.casefold()
            query = query.capitalize()
            or_lookup = (Q(name__icontains=query))
            qs = qs.filter(or_lookup)
        return qs


class ArticleCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='активный'
    )

    def __str__(self):
        return self.name

    def get_category_query_set(self):
        queryset = self.objects.all()
        return queryset


class Article(models.Model, ModelClassNameMixin):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='articles')
    title = models.CharField(max_length=200)
    article_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)
    published_date = models.DateTimeField(blank=True, null=True)
    is_published = models.BooleanField(default=False, null=True)
    is_banned = models.BooleanField(default=False, null=True)
    category = models.ForeignKey(ArticleCategory, verbose_name='Категория',
                                 on_delete=models.CASCADE)
    likes = models.ManyToManyField(
        User, blank=True, related_name='article_likes'),
    image = models.ImageField(upload_to='article_photos', blank=True,
                              null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model, ModelClassNameMixin):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    is_banned = models.BooleanField(default=None, null=True)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
    likes = models.ManyToManyField(
        User, blank=True, related_name='comment_likes')

    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_at').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

command_project/mainapp/forms.py
from django import forms
from .models import Article, Comment


class CreateArticleForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Article
        fields = ['title', 'category', 'image', 'article_text', 'is_published']
        labels = {
            'title': 'Введите заголовок',
            'article_text': "Ваши мысли тут",
            'is_published': 'Опубликовать сразу?'
        }

    def __init__(self, *args, **kwargs):
        super(CreateArticleForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Введите комментарий'}

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

command_project/mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Sum
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from authapp.models import User
from moderation.models import Report
from .forms import CommentForm, CreateArticleForm
from .models import ArticleCategory, Article, Comment


class AuthorTestMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user == self.get_object().author


class BanTestMixin(UserPassesTestMixin):
    def test_func(self):
        self.permission_denied_message = 'Вы забанены'
        return not self.request.user.is_banned


def get_top10_articles():
    top10_articles = Article.objects.annotate(
        cnt=Count('likes')).order_by('-cnt')[:5]
    return top10_articles


class ArticlesView(ListView):
    model = Article
    ordering = '-created_date'
    paginate_by = 5
    template_name = 'mainapp/articles.html'
    context_object_name = 'articles'
    extra_context = {
        'title': 'Habr',
        'categories': ArticleCategory.objects.all(),
        'top10_articles': get_top10_articles(),
    }

    def get_queryset(self):
        queryset = super(ArticlesView, self).get_queryset().order_by(
            '-created_date')
        queryset = queryset.filter(is_published=True, is_banned=False)
        if 'pk' in self.kwargs:
            if self.kwargs['pk'] == 0:
                return queryset
            elif self.kwargs['pk'] != 0:
                queryset = queryset.filter(category_id__pk=self.kwargs['pk'])
                return queryset
        else:
            return queryset


@method_decorator(csrf_exempt, name='dispatch')
class ArticleView(DetailView):
    model = Article
    template_name = 'mainapp/article.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleView, self).get_context_data(**kwargs)
        context['title'] = 'Habr'
        context['categories'] = ArticleCategory.objects.all()
        context['form'] = CommentForm()
        comments = self.get_comments()
        context['comments'] = comments
        context['same_articles'] = self.get_same_articles()
        return context

    def get_comments(self):
        comments = Comment.objects.filter(article__pk=self.kwargs['pk'])
        for comment in comments:
            if comment.is_banned:
                comment.text = 'Комментарий заблокирован модератором'
        return comments

    def get_same_articles(self):

        category = self.object.category
        same_articles = self.model.objects.filter(
            category=category).annotate(cnt=Count('likes'))
        return same_articles.order_by('-cnt')[:5]


@method_decorator(csrf_exempt, name='dispatch')
class ArticleCreateView(LoginRequiredMixin, BanTestMixin, CreateView):
    model = Article
    template_name = 'mainapp/create_article.html'
    form_class = CreateArticleForm
    pk = None
    login_url = '/auth/login/'

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        self.object = article
        self.pk = article.pk
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('mainapp:article', kwargs={'pk': self.pk})


@method_decorator(csrf_exempt, name='dispatch')
class ArticleUpdateView(LoginRequiredMixin, AuthorTestMixin, UpdateView):
    model = Article
    template_name = 'mainapp/create_article.html'
    form_class = CreateArticleForm
    pk = None
    login_url = '/auth/login/'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('mainapp:article', kwargs={'pk': self.pk})

    def form_valid(self, form):
        self.pk = self.object.pk
        return super(ArticleUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        content = super(ArticleUpdateView, self).get_context_data(**kwargs)
        content['title'] = 'Редактирование статьи'
        content['article'] = Article.objects.get(pk=pk)
        return content

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return Article.objects.get(pk=pk)


@method_decorator(csrf_exempt, name='dispatch')
class ArticleDeleteView(LoginRequiredMixin, AuthorTestMixin, DeleteView):
    model = Article
    login_url = '/auth/login/'
    success_url = reverse_lazy('mainapp:articles')

    def form_valid(self, form):
        self.object = self.get_object()
        if self.object.is_published:
            self.object.is_published = False
        else:
            self.object.is_published = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@method_decorator(csrf_exempt, name='dispatch')
class ArticlePublishView(LoginRequiredMixin, AuthorTestMixin, UpdateView):
    model = Article
    login_url = '/auth/login/'
    success_url = reverse_lazy('mainapp:articles')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.is_published = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


def about_us(request):
    title = 'о нас'
    content = {'title': title}

    return render(request, 'mainapp/about_us.html', content)


@method_decorator(csrf_exempt, name='dispatch')
class CommentView(LoginRequiredMixin, BanTestMixin, View):
    login_url = '/auth/login/'
    permission_denied_message = 'вы не авторизованны'

    def post(self, request, pk, *args, **kwargs):
        form = CommentForm(request.POST)
        article = Article.objects.get(pk=pk)

        if form.is_valid():
            text = form.cleaned_data['text']
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.article = article
            new_comment.save()

            comments = Comment.objects.filter(
                article=article).order_by('-created_at')
            context = {
                'article': article,
                'form': form,
                'comments': comments,
            }
            if '@moderator' in text:
                report = Report.create(object_pk=article, user=request.user)
                report.save()
        return HttpResponseRedirect(reverse('mainapp:article', kwargs={'pk': article.pk}))


@method_decorator(csrf_exempt, name='dispatch')
class CommentReplyView(LoginRequiredMixin, BanTestMixin, View):
    def post(self, request, article_pk, pk, *args, **kwargs):
        article = Article.objects.get(pk=article_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.article = article
            new_comment.parent = parent_comment
            new_comment.save()
            if '@moderator' in text:
                report = Report.create(
                    object_pk=parent_comment, user=request.user)
                report.save()

        comments = Comment.objects.filter(
            article=article).order_by('-created_at')
        context = {
            'article': article,
            'form': form,
            'comments': comments,
        }
        return HttpResponseRedirect(reverse('mainapp:article', kwargs={'pk': article_pk}))


@method_decorator(csrf_exempt, name='dispatch')
class LikeSwitcher(LoginRequiredMixin, BanTestMixin, View):
    login_url = '/auth/login/'
    permission_denied_message = 'вы не авторизованны'

    def handle_no_permission(self):
        self.request.path = self.request.META['HTTP_REFERER'].replace(
            self.request.META['HTTP_ORIGIN'], '')
        if self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            try:

                _handle_no_permission = super(
                    LikeSwitcher, self).handle_no_permission()
                if _handle_no_permission.status_code == 302:
                    return JsonResponse({'url': _handle_no_permission.url}, status=302)
            except PermissionDenied:
                return JsonResponse({"error": self.permission_denied_message}, status=403)
        return super(LikeSwitcher, self).handle_no_permission()

    def post(self, request, model, pk, *args, **kwargs):
        models = {
            Article.__name__: Article,
            Comment.__name__: Comment,
            User.__name__: User,
        }
        is_liked = False
        model_to_liked = models[model].objects.get(pk=pk)
        for like in model_to_liked.likes.all():
            if like == request.user:
                is_liked = True
                break
        if is_liked:
            model_to_liked.likes.remove(request.user)
        else:
            model_to_liked.likes.add(request.user)
        next = request.POST.get('next', '/')
        if self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            return JsonResponse({"likes_count": model_to_liked.likes.count()}, status=200)

        else:
            return HttpResponseRedirect(next)


def help(request):
    title = 'Помощь'
    content = {'title': title}

    return render(request, 'mainapp/help.html', content)

command_project/mainapp/templates/mainapp/includes/comments.html
{% load static %}

<section>
    <div class="container my-5 py-5">

        <div class="row d-flex justify-content-center">
            <div class="col-md-12 col-lg-10 col-xl-8">

                <div class="card">
                    <div class="card-body p-4">
                        {% if article.is_published %}
                        <h4 class="text-center mb-4 pb-2">Комментарии</h4>
                        {% endif %}
                        <div class="row">
                            <div class="col">
                                {% for comment in comments %}
                                {% if comment.is_parent %}
                                <div class="d-flex flex-start">
                                    <img
                                            class="rounded-circle shadow-1-strong me-3"
                                            src="{% if comment.author.avatar_link %} {{ comment.author.avatar_link.url }} {% endif %}"
                                            alt="avatar"
                                            width="65"
                                            height="65"
                                    />
                                    <div class="flex-grow-1 flex-shrink-1">
                                        <div>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <p class="mb-1">
                                                    <a class="link-dark" href="{% url 'auth:users_detail' comment.author_id %}">{{ comment.author }} </a>
                                                    <span class="small text-align left">написал {{ comment.created_at|date:"d.m.Y" }} {{ comment.created_at|time:"H:i" }} </span>
                                                </p>

                                            </div>
                                            <p class="small mb-0 u-align-left">
                                                {{ comment.text }}
                                            </p>
                                        </div>
                                    </div>
                                    {% if request.user.is_authenticated %}
                                    {% include "mainapp/includes/like.html" with model=comment text="лайк комментарию" %}
                                    {% endif %}

                                    {% if request.user.is_staff %}
                                    {% if not article.is_banned %}
                                    <form method="POST" action="{% url 'mod:ban' model='comment' pk=comment.pk %}">
                                        {% csrf_token %}
                                        <button class="btn btn-link btn-xs" type="submit" name="next" value="{{ request.path }}">
                                            <i class="fas fa-ban text-muted"></i>
                                        </button>
                                    </form>
                                    {% endif %}
                                    {% endif %}

                                </div>
                                {% if request.user.is_authenticated %}
                                <div align="right">
                                    <button class="btn btn-link">
                                        <i class="fas fa-reply fa-xs" onclick="commentReplyToggle('{{ comment.pk }}')">
                                            Ответить
                                        </i>
                                    </button>
                                </div>
                                <div class="row justify-content-center mt-3 mb-5 d-none" id="{{ comment.pk }}">
                                    <div class="col">
                                        <form method="POST" action="{% url 'mainapp:comment-reply' article.pk comment.pk %}">
                                            {% csrf_token %}
                                            {{ form }}
                                            <div class="d-grid gap-2">
                                                <button class="btn btn-outline-dark">Отправить</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                                {% endif %}
                                {% for child_comment in comment.children %}
                                <div class="d-flex flex-end mt-4 ms-5">
                                    <a class="me-3 ml-5" href="#">
                                        <img
                                                class="rounded-circle shadow-1-strong"
                                                src="{% if child_comment.author.avatar_link %} {{ child_comment.author.avatar_link.url }} {% endif %}"
                                                alt="avatar"
                                                width="65"
                                                height="65"
                                        />
                                    </a>
                                    <div class="flex-grow-1 flex-shrink-1">
                                        <div>
                                            <div class="d-flex justify-content-between align-items-center">
                                                <p class="mb-1">
                                                    <a class="link-dark" href="{% url 'auth:users_detail' child_comment.author.pk %}">
                                                        {{ child_comment.author }}</a> <span class="small "> ответил {{ child_comment.created_at}} </span>
                                                </p>
                                            </div>
                                            <p class="small mb-0 u-align-left">
                                                {{ child_comment.text }}
                                            </p>
                                        </div>
                                    </div>

                                    <div align="top">
                                        {% if request.user.is_authenticated %}
                                        {% include "mainapp/includes/like.html" with model=child_comment text="лайк комментарию" %}
                                        {% endif %}

                                    </div>
                                    <div align="top">
                                        {% if request.user.is_staff %}
                                        {% if not article.is_banned %}
                                        <form method="POST" action="{% url 'mod:ban' model='comment' pk=comment.pk %}">
                                            {% csrf_token %}
                                            <button class="btn btn-link btn-xs" type="submit" name="next" value="{{ request.path }}">
                                                <i class="fas fa-ban text-muted"></i>
                                            </button>
                                        </form>
                                        {% endif %}
                                        {% endif %}

                                    </div>




                                </div>
                                {% endfor %}
                                {% endif %}
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                {% if request.user.is_authenticated %}
                {% if article.is_published %}
                <form class="u-align-center" method="POST" action="{% url 'mainapp:comment' article.pk %}">
                    {% csrf_token %}
                    <p></p>
                    {{ form }}
                    <input type="submit" value="Отправить"/>
                </form>
                {% endif %}
                {% endif %}
                <br>
                {% if not request.user.is_authenticated %}
                    Хотите оценить статью или оставить комментарий?
                    <a href="{% url 'auth:users_create' %}?next={{request.path}}" target="_blank">Зарегистрируйтесь!</a>
                {% endif %}
            </div>


        </div>
    </div>
</section>

command_project/mainapp/templates/mainapp/includes/inc_categories.html
<div>

    <ul class="nav nav-tabs justify-content-center">
        {% for category in categories %}
        <li class="nav-item">
            <a class="nav-link link-dark" href="{% url 'mainapp:category' category.pk %}">{{ category.name }}</a>
        </li>
        {% endfor %}
    </ul>

</div>

command_project/mainapp/templates/mainapp/includes/inc_footer.html
{% load static %}

<footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-8da6">
    <div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-small-text u-text u-text-variant u-text-1"> 2022(с) Bad Rhymes</p>
    </div>
</footer>
<section class="u-backlink u-clearfix u-grey-80">
</section>

command_project/mainapp/templates/mainapp/includes/like.html
<form id="{{ model.model_name }}-{{ model.pk }}-like-form" method="POST" >
{#    #action="{% url 'mainapp:like' model.model_name model.pk %}"#}
    {% csrf_token %}
    <div class="d-flex flex-row align-items-center">
        <div class="col">
            <button class="btn btn-link btn-xs" type="submit" name="next" value="{{ request.path }}">
                <i class="fas fa-thumbs-up mx-1 fa-s text-muted"></i>
                <span class="small text-muted mb-0" id="{{ model.model_name }}-{{ model.pk }}-likes-count">
                    {{ model.likes.all.count }}
                </span>
            </button>
        </div>
    </div>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  $(document).ready(function () {
      $('#{{ model.model_name }}-{{ model.pk }}-like-form').submit(function () {
          $.ajax({
              type: $(this).attr('method'),
              url: "{% url 'mainapp:like' model.model_name model.pk %}",
              success: function (response) {
                  $('#{{ model.model_name }}-{{ model.pk }}-likes-count').text(function () {
                      return response.likes_count;
                      }
                  )
              },
              error: function (response) {
                  if (response.status === 302) {
                      alert('авторизируйтесь');
                      window.location.href = response.responseJSON.url;
                  }
                  else if (response.status === 403) {
                      alert(response.responseJSON.error)
                  }
              }
          });
          return false;
      });
  })
</script>