command_project/authapp/urls.py
from django.urls import path
from .views import UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, UserLoginView
from django.contrib.auth.views import LogoutView


app_name = 'auth'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('reg/', UserCreateView.as_view(), name='users_create'),
    path('edit/', UserUpdateView.as_view(), name='users_update'),
    path('remove/', UserDeleteView.as_view(), name='users_remove'),
]

command_project/habr/urls.py
# """habr URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('moderation.urls', namespace='mod')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('django.contrib.auth.urls')),
    path('search/', include('searchapp.urls', namespace='search')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

command_project/authapp/models.py
from datetime import datetime

import pytz
from django.db import models
from django.contrib.auth.models import AbstractUser

from mainapp.mixins import ModelClassNameMixin


class User(AbstractUser, ModelClassNameMixin):
    user_about = models.CharField(max_length=1024, blank=True)
    avatar_link = models.ImageField(upload_to='users_images', blank=True)
    blocked_time = models.DateTimeField(null=True, blank=True)
    email = models.EmailField(blank=True, unique=True)
    likes = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='user_likes')

    @property
    def is_banned(self):
        if self.blocked_time is not None:
            now = pytz.utc.localize(datetime.now())
            block_duration = now - self.blocked_time
            if block_duration.days < 14:
                return True
            else:
                self.blocked_time = None
                self.save()
                return False
        else:
            return False

command_project/authapp/forms.py
import re
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Подтвердите пароль'}))
    avatar_link = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(UserRegisterForm, self).clean()
        username = cleaned_data.get("username")
        password = cleaned_data.get("password1")
        email = cleaned_data.get("email")
        confirm_password = cleaned_data.get("password2")
        pattern = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$'

        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                "Никнейм уже занят."
            )
        elif len(username) < 3 or len(username) > 15:
            raise forms.ValidationError(
                "Никнейм должен быть больше (от 3 до 15 символов)."
            )
        elif User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Данный email уже зарегистрирован на сайте."
            )
        elif password != confirm_password:
            raise forms.ValidationError(
                "Пароли не совпадают."
            )
        elif len(password) <= 6:
            raise forms.ValidationError(
                "Пароль должен содержать не менее 6 символов."
            )
        elif r'\w' not in password.split() and re.match(pattern, password) is None and (
                password.isupper() or password.islower()):
            raise forms.ValidationError(
                "Пароль должен содержать строчные латинские буквы в верхнем и нижнем регистрах."
            )
        

class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput())
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    avatar_link = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('username', 'avatar_link', 'first_name', 'last_name', 'user_about')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')

command_project/authapp/views.py
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
# from django_registration.backends.activation.views import RegistrationView
from django.contrib.auth.views import LoginView

from .models import User
from .forms import UserRegisterForm, UserProfileForm, UserLoginForm
from mainapp.models import Article, Comment


# CRUD - Create Read Update Delete
class UserDetailView(DetailView):
    model = User
    template_name = 'authapp/users-detail.html'

    def dispatch(self, request, *args, **kwargs):
        return super(UserDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['title'] = 'Профиль'
        content['user'] = self.request.user
        content['user_detail'] = self.get_object()
        content['rating'] = self.get_rating()
        content['published_articles'] = Article.objects.filter(
            author__id=self.get_object().id, is_published=True)
        content['draft_articles'] = Article.objects.filter(
            author__id=self.get_object().id, is_published=False)
        content['draftnull_articles'] = Article.objects.filter(
            author__id=self.get_object().id, is_published=None)

        if self.request.user.is_authenticated:
            content['user_check'] = User.objects.get(
                username=self.request.user)
            if content['user_check'].id == self.get_object().id:
                content['edit_visible'] = 'True'
            else:
                content['edit_visible'] = 'False'
        else:
            content['edit_visible'] = 'False'
        return content

    def get_rating(self):
        articles_likes = Article.objects.filter(
            author__id=self.get_object().id).count()
        comments_likes = Comment.objects.filter(
            author__id=self.get_object().id).count()
        rating = articles_likes + comments_likes
        return rating


class UserCreateView(CreateView):
    model = User
    template_name = 'authapp/users-create.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('mainapp:articles')


    def dispatch(self, request, *args, **kwargs):
        return super(UserCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['title'] = 'Регистрация'
        next = ''
        if self.request.GET:
            next = self.request.GET['next']
        if next != '':
            content['next'] = next
        return content



class UserUpdateView(UpdateView):
    model = User
    template_name = 'authapp/users-update-delete.html'
    form_class = UserProfileForm

    def get_context_data(self, **kwargs):
        content = super(UserUpdateView, self).get_context_data(**kwargs)
        content['title'] = 'Редактирование пользователя'
        content['user'] = User.objects.get(username=self.request.user)
        return content

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user)

    def get_success_url(self):
        profile_id = User.objects.get(username=self.request.user).id
        return reverse_lazy('auth:users_detail', kwargs={'pk': profile_id})


class UserDeleteView(DeleteView):
    model = User
    template_name = 'authapp/users-update-delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = 0
        self.object.save()

    def get_object(self, queryset=None):
        return User.objects.get(username=self.request.user)

    def get_success_url(self):
        return reverse_lazy('auth:login')

class UserLoginView(LoginView):
    template_name = 'authapp/login.html'
    redirect_field_name = 'next'
    authentication_form = UserLoginForm

command_project/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} Авторизация {% endblock %}
{% block content %}

<div class="login_form1">
    {% if messages or form.non_field_errors %}
    <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
            alert-dismissible fade show" role="alert"
         style="margin-top: 50px;">
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% else %}
        {% for error in form.non_field_errors %}
        {{ error }}
        {% endfor %}
        {% endif %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}

    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3></div>
        <div class="card-body">
            {% if next %}
            <form action="{% url 'auth:login' %}?next={{next}}" method="post">
                {%else%}
                <form action="{% url 'auth:login' %}" method="post" enctype="multipart/form-data">
                    {% endif %}
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1 av" class="form-control"
                               id="{{ form.username.id_for_label }}">Никнейм</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label type="text" class="small mb-1 av" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <input class="btn btn-primary b-avt" type="submit" value="Авторизоваться">
                    </div>
                </form>
        </div>
        <div class="card-footer text-center">
            <div class="small"><a href="{% url 'auth:users_create' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
        </div>
    </div>
</div>
{% endblock %}

command_project/authapp/templates/authapp/users-create.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} Регистрация {% endblock %}
{% block content %}
<div class="u-align-center">
<h1 class="mt-4">Создание пользователя</h1>
{% if messages or form.non_field_errors or form.email.errors or form.password.errors%}
<div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
            alert-dismissible fade show" role="alert"
     style="margin-top: 50px;">
    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% elif form.non_field_errors%}
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
    {% elif form.email.errors %}
        {% for error in form.email.errors %}
            {{error}}
        {% endfor %}
    {% else %}
        {% for error in form.password.errors %}
            {{error}}
        {% endfor %}
    {% endif %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}


{% if next %}
<form action="{% url 'auth:users_create' %}?next={{next}}" method="post">
    {% csrf_token %}
    {%else%}
    <form action="{% url 'auth:users_create' %}" method="post" enctype="multipart/form-data">
        {% endif %}
        {% csrf_token %}
        <div class="reg_form_main">
            <div class="form-row" style="width: 50%; margin-left: 25%;">
                <div class="reg-form-1">
                    <label class="mid mb-1" for="{{ form.username.id_for_label }}">Никнейм</label>
                    <input class="form-control" {{ form.username }}
                </div>
                <div class="reg-form-1">
                    <label class="mid mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    <input class="form-control" {{ form.email }}
                </div>
                <div class="reg-form-1">
                    <label class="mid mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                    <input class="form-control" {{ form.password1 }}
                </div>
                <div class="reg-form-1>
                        <label class=" mid mb-1
                " for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                <input class="form-control" {{ form.password2 }}
            </div>
            <div class="reg-form-1 save">
                <input class="btn btn-outline-dark" type="submit" value="Сохранить">
            </div>
        </div>
        </div>
    </form>
</form>


{% endblock %}

command_project/authapp/templates/authapp/users-update-delete.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} Редактирование пользователя {% endblock %}
{% block content %}
<secton class="u-align-center">
    <h1 class="mt-4" xmlns="http://www.w3.org/1999/html">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body " style="width: 50%; margin-left: 25%;">
        <form action="{% url 'auth:users_update' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="reg-form-1">
                    <div class="form-group">
                        <label class="mid mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        <input class="form-control" {{ form.first_name }} </div>
                    </div>
                    <div class="reg-form-1">
                        <div class="form-group">
                            <label class="mid mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            <input class="form-control" {{ form.last_name }} </div>
                        </div>
                        <div class="reg-form-1">
                            <label for="{{ form.avatar_link.id_for_label }}" class="form-label mid mb-2">Выберите
                                изображение</label>
                            {{ form.avatar_link }}
                        </div>
                        <div class="reg-form-1">
                            <div class="form-group">
                                <label class="mid mb-1" for="{{ form.user_about.id_for_label }}">Описание</label>
                                <input class="form-control" {{ form.user_about }} </div>
                            </div>
                        </div>
                        <div class="reg-form-1">
                            <label class="mid mb-1" for="{{ form.username.id_for_label }}">Никнейм</label>
                            <input class="form-control" {{ form.username }} </div>
                            <div class="reg-form-1" style="margin-top: 33px;">
                                <input class="btn btn-outline-dark" style="width: 120px;" type="submit"
                                    value="Сохранить">
                            </div>
        </form>
        <div class="reg-form-1" style="margin-top: 33px; ">
            <form action="{% url 'auth:users_remove' %}" method="post"
                onclick="return confirm('Вы действительно хотите удалить этот аккаунт?')">
                {% csrf_token %}
                <button onclick="return confirm('Вы уверенны, что хотите удалить профиль?');" class="btn btn-outline
                -dark" style="width: 120px;"> Удалить
                </button>
            </form>
        </div>
    </div>

    </div>
</secton>
{% endblock %}