command_project/authapp/urls.py
from django.urls import path
from .views import UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, UserLoginView
from django.contrib.auth.views import LogoutView


app_name = 'auth'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('reg/', UserCreateView.as_view(), name='users_create'),
    path('edit/', UserUpdateView.as_view(), name='users_update'),
    path('remove/', UserDeleteView.as_view(), name='users_remove'),
]

command_project/habr/urls.py
# """habr URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('moderation.urls', namespace='mod')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('django.contrib.auth.urls')),
    path('search/', include('searchapp.urls', namespace='search')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

command_project/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp
from .views import ArticlesView, ArticleView, ArticleCreateView, \
    ArticleUpdateView, ArticlePublishView, ArticleDeleteView, LikeSwitcher


app_name = 'mainapp'

urlpatterns = [
    path('', ArticlesView.as_view(), name='articles'),
    path('category/<int:pk>/', ArticlesView.as_view(), name='category'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article'),
    path('article/create/', ArticleCreateView.as_view(), name='create_article'),
    path('article/delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_article'),
    path('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='update_article'),
    path('article/publish/<int:pk>/', ArticlePublishView.as_view(), name='publish_article'),
    path('about_us/', mainapp.about_us, name='about_us'),
    path('article/<int:article_pk>/comment/reply/<int:pk>', mainapp.CommentReplyView.as_view(), name='comment-reply'),
    path('article/<int:pk>/comment/', mainapp.CommentView.as_view(), name='comment'),
    path('like/<str:model>/<int:pk>', LikeSwitcher.as_view(), name='like'),
    path('help/', mainapp.help, name='help'),
]

command_project/searchapp/urls.py
from django.urls import path

from searchapp.views import SearchArticleList

app_name = 'search'

urlpatterns = [
    path('search/articles', SearchArticleList.as_view(), name='search_article_results'),
]

command_project/searchapp/models.py
from django.db import models

# Create your models here.

command_project/searchapp/views.py
from django.db.models import Q
from django.views.generic import ListView
from mainapp.models import Article, ArticleCategory


class SearchArticleList(ListView):
    model = Article
    paginate_by = 100
    template_name = 'searchapp/search_article_results.html'
    extra_context = {
        'title': 'Habr',
        'categories': ArticleCategory.objects.all(),
    }

    def get_context_data(self, **kwargs):
        context = super(SearchArticleList, self).get_context_data(**kwargs)

        q = self.request.GET.get('search')
        sort = self.request.GET.getlist('sort')
        context['search_name'] = q
        if q:

            queryset = Article.objects.filter(Q(title__icontains=q.capitalize()) | Q(title__icontains=q.lower())
                                        | Q(title__icontains=q.upper()) | Q(article_text__icontains=q.capitalize())
                                        | Q(article_text__icontains=q.lower()) | Q(article_text__icontains=q.upper()))

            if sort:
                queryset = queryset.order_by(*sort)
            else:
                queryset.order_by('-likes')

            context['articles'] = queryset

        return context

command_project/searchapp/templates/searchapp/search_article_results.html
{% extends 'mainapp/base.html' %}
{% block title %} Результаты поиска {% endblock %}
{% block content %}

<section class="u-align-center">
    <h1>результаты поиска по "{{ search_name }}" среди статей</h1>


    <form method="get">
        <button type="submit" class="btn btn-sm btn-primary btn-raised mr-3" name="search" value="{{ search_name }}">
            Сортировать </button>
        <input name="sort" type="checkbox" value="-likes" {{ likes }}>"сначала рейтинг выше"
        <input name="sort" type="checkbox" value="likes" {{ likes }}>"сначала рейтинг ниже"
        <input name="sort" type="checkbox" value="-created_date" {{ created_date }}>"сначала новые"
        <input name="sort" type="checkbox" value="created_date" {{ created_date }}>"сначала старые"
    </form>
<br>

    {% if articles %}
        {% for object in articles %}
            {% if not object.is_banned %}
                <div class="card col-lg-6 offset-lg-3 mb-3">
                    <div class="card-body">
                        <a>
                          <h2 class="card-title my-3"> {{ object.title }} </h2>
                        </a>
                        <div class="text-muted mb-3">
                            <div>
                                <span>created: {{ object.created_date|date:"N j Y" }} |</span>
                                <span>Автор: {{ object.user }}</span>
                                <span>Категория: {{ object.category }}</span>
                            </div>
                        </div>
                        <p class="card-text">{{ object.article_text|truncatewords:100 }}</p>
                        <a class='btn btn-light' href="{% url 'mainapp:article' object.id %}">Читать дальше ...</a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>Не найдено ничего по вашему запросу<br>Попробуйте повторить запрос с другой формулировкой</p>
    {% endif %}

    <!-- Pagination -->
  <div class="row">
    <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
      <ul class="pagination">


        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
        <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}

      </ul>
    </nav>
  </div>
  <!-- /Pagination -->
{% endblock %}

    </section>

command_project/searchapp/templates/searchapp/search_results.html
{% extends 'mainapp/base.html' %}
{% block title %} Результаты поиска {% endblock %}
{% block content %}
    <h1>результаты поиска по «{{ search_name }}»</h1>
    {% if object_list %}
        {if not object.is_banned %}
                {% for object in object_list %}
                    {% if object.title %}
                        <div class="card col-lg-6 offset-lg-3 mb-3">
                            <div class="card-body">
                                <a>
                                  <h2 class="card-title my-3"> {{ object.title }} </h2>
                                </a>
                                <div class="text-muted mb-3">
                                    <div>
                                        <span>created: {{ object.created_date|date:"N j Y" }} |</span>
                                        <span>Автор: {{ object.user }}</span>
                                        <span>Категория: {{ object.category }}</span>
                                    </div>
                                </div>
                                <p class="card-text">{{ object.article_text|truncatewords:20 }}</p>
                                <a class='btn btn-light' href="{% url 'mainapp:article' object.id %}">Read more ...</a>
                            </div>
                        </div>
                    {% elif object.name %}
                        <div class="card col-lg-6 offset-lg-3 mb-3">
                            <div class="card-body">
                                <a>
                                  <h2 class="card-title my-3"> Категория {{ object.name }} </h2>
                                </a>
                                <p class="card-text">{{ object.description|truncatewords:20 }}</p>
                                <a class='btn btn-light' href="{% url 'mainapp:category' object.id %}">
                                    Перейти на страницу категории</a>
                            </div>
                        </div>
                    {% else %}
                        <div class="card col-lg-6 offset-lg-3 mb-3">
                            <div class="card-body">
                                <a>
                                  <h2 class="card-title my-3"> {{ object.username }} </h2>
                                </a>
                                <div class="text-muted mb-3">
                                    <span><img height="150" src="{% if object.avatar_link %}
                                    {{ object.avatar_link.url }} {% endif %}" alt=""></span>
                                    <div>
                                        <span>Имя: {{ object.first_name }} |</span>
                                        <span>Фамилия: {{ object.last_name }}</span>
                                    </div>
                                </div>
                                <p class="card-text">{{ object.user_about|truncatewords:20 }}</p>
                                <a class='btn btn-light' href="{% url 'auth:users_detail' object.id %}">
                                    Перейти на страницу профиля</a>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>Не найдено ничего по вашему запросу<br>Попробуйте повторить запрос с другой формулировкой</p>
        {% endif %}
    {% endif %}

    <!-- Pagination -->
  <div class="row">
    <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
      <ul class="pagination">


        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Previous</a>
        </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
        <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
        {% endif %}

      </ul>
    </nav>
  </div>
  <!-- /Pagination -->
{% endblock %}

command_project/searchapp/templates/searchapp/searchbar.html
<form  action="{% url 'search:search_article_results' %}" method="get" class="u-border-1 u-border-grey-15 u-search u-search-right u-search-1">
            <button class="u-search-button" type="submit">
            <span class="u-search-icon u-spacing-10 u-text-grey-40">
              <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 56.966 56.966" style=""><use
                      xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-b04b"></use></svg>
              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"
                   id="svg-b04b" x="0px" y="0px" viewBox="0 0 56.966 56.966"
                   style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" class="u-svg-content"><path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>
            </span>
            </button>

{#            <button formaction="{% url 'search:search_user_result' %}" class="u-search-button" type="submit">#}
{#            <span class="u-search-icon u-spacing-10 u-text-grey-40">#}
{#              <svg class="u-svg-link" preserveAspectRatio="xMidYMin slice" viewBox="0 0 56.966 56.966" style=""><use#}
{#                      xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#svg-b04b"></use></svg>#}
{#              <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1"#}
{#                   id="svg-b04b" x="0px" y="0px" viewBox="0 0 56.966 56.966"#}
{#                   style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" class="u-svg-content"><path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z"></path><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g><g></g></svg>#}
{#            </span>#}
            </button>

            <input class="u-search-input" type="text" name="search" placeholder="Search" >


</form>