command_project/authapp/urls.py
from django.urls import path
from .views import UserDetailView, UserCreateView, UserUpdateView, UserDeleteView, UserLoginView
from django.contrib.auth.views import LogoutView


app_name = 'auth'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('reg/', UserCreateView.as_view(), name='users_create'),
    path('edit/', UserUpdateView.as_view(), name='users_update'),
    path('remove/', UserDeleteView.as_view(), name='users_remove'),
]

command_project/habr/urls.py
# """habr URL Configuration
#
# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='main')),
    path('', include('moderation.urls', namespace='mod')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('django.contrib.auth.urls')),
    path('search/', include('searchapp.urls', namespace='search')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

command_project/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp
from .views import ArticlesView, ArticleView, ArticleCreateView, \
    ArticleUpdateView, ArticlePublishView, ArticleDeleteView, LikeSwitcher


app_name = 'mainapp'

urlpatterns = [
    path('', ArticlesView.as_view(), name='articles'),
    path('category/<int:pk>/', ArticlesView.as_view(), name='category'),
    path('article/<int:pk>/', ArticleView.as_view(), name='article'),
    path('article/create/', ArticleCreateView.as_view(), name='create_article'),
    path('article/delete/<int:pk>/', ArticleDeleteView.as_view(), name='delete_article'),
    path('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='update_article'),
    path('article/publish/<int:pk>/', ArticlePublishView.as_view(), name='publish_article'),
    path('about_us/', mainapp.about_us, name='about_us'),
    path('article/<int:article_pk>/comment/reply/<int:pk>', mainapp.CommentReplyView.as_view(), name='comment-reply'),
    path('article/<int:pk>/comment/', mainapp.CommentView.as_view(), name='comment'),
    path('like/<str:model>/<int:pk>', LikeSwitcher.as_view(), name='like'),
    path('help/', mainapp.help, name='help'),
]

command_project/moderation/urls.py
from django.urls import path
from .views import change_moderator_status, ModeratorPage, Ban, Unban

app_name = 'moderation'


urlpatterns = [
    path('moderator_page', ModeratorPage.as_view(), name='moderator_page'),
    path('change_moderator_status/<int:pk>/', change_moderator_status, name='change_moderator_status'),
    path('ban/<str:model>/<int:pk>', Ban.as_view(), name='ban'),
    path('unban/<str:model>/<int:pk>', Unban.as_view(), name='unban'),
               ]

command_project/mainapp/models.py
from django.db import models
from django.utils import timezone

from authapp.models import User
from django.db.models import Q

from mainapp.mixins import ModelClassNameMixin


class ArticleCategoryManager(models.Manager):
    use_for_related_fields = True

    def search(self, query=None):
        qs = self.get_queryset()
        if query:
            query = query.casefold()
            query = query.capitalize()
            or_lookup = (Q(name__icontains=query))
            qs = qs.filter(or_lookup)
        return qs


class ArticleCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name='активный'
    )

    def __str__(self):
        return self.name

    def get_category_query_set(self):
        queryset = self.objects.all()
        return queryset


class Article(models.Model, ModelClassNameMixin):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='articles')
    title = models.CharField(max_length=200)
    article_text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(blank=True, null=True)
    published_date = models.DateTimeField(blank=True, null=True)
    is_published = models.BooleanField(default=False, null=True)
    is_banned = models.BooleanField(default=False, null=True)
    category = models.ForeignKey(ArticleCategory, verbose_name='Категория',
                                 on_delete=models.CASCADE)
    likes = models.ManyToManyField(
        User, blank=True, related_name='article_likes'),
    image = models.ImageField(upload_to='article_photos', blank=True,
                              null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model, ModelClassNameMixin):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    text = models.TextField()
    is_banned = models.BooleanField(default=None, null=True)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, related_name='+')
    likes = models.ManyToManyField(
        User, blank=True, related_name='comment_likes')

    @property
    def children(self):
        return Comment.objects.filter(parent=self).order_by('-created_at').all()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False

command_project/mainapp/forms.py
from django import forms
from .models import Article, Comment


class CreateArticleForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = Article
        fields = ['title', 'category', 'image', 'article_text', 'is_published']
        labels = {
            'title': 'Введите заголовок',
            'article_text': "Ваши мысли тут",
            'is_published': 'Опубликовать сразу?'
        }

    def __init__(self, *args, **kwargs):
        super(CreateArticleForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Введите комментарий'}

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

command_project/mainapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count, Sum
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render

from authapp.models import User
from moderation.models import Report
from .forms import CommentForm, CreateArticleForm
from .models import ArticleCategory, Article, Comment


class AuthorTestMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user == self.get_object().author


class BanTestMixin(UserPassesTestMixin):
    def test_func(self):
        self.permission_denied_message = 'Вы забанены'
        return not self.request.user.is_banned


def get_top10_articles():
    top10_articles = Article.objects.annotate(
        cnt=Count('likes')).order_by('-cnt')[:5]
    return top10_articles


class ArticlesView(ListView):
    model = Article
    ordering = '-created_date'
    paginate_by = 5
    template_name = 'mainapp/articles.html'
    context_object_name = 'articles'
    extra_context = {
        'title': 'Habr',
        'categories': ArticleCategory.objects.all(),
        'top10_articles': get_top10_articles(),
    }

    def get_queryset(self):
        queryset = super(ArticlesView, self).get_queryset().order_by(
            '-created_date')
        queryset = queryset.filter(is_published=True, is_banned=False)
        if 'pk' in self.kwargs:
            if self.kwargs['pk'] == 0:
                return queryset
            elif self.kwargs['pk'] != 0:
                queryset = queryset.filter(category_id__pk=self.kwargs['pk'])
                return queryset
        else:
            return queryset


@method_decorator(csrf_exempt, name='dispatch')
class ArticleView(DetailView):
    model = Article
    template_name = 'mainapp/article.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleView, self).get_context_data(**kwargs)
        context['title'] = 'Habr'
        context['categories'] = ArticleCategory.objects.all()
        context['form'] = CommentForm()
        comments = self.get_comments()
        context['comments'] = comments
        context['same_articles'] = self.get_same_articles()
        return context

    def get_comments(self):
        comments = Comment.objects.filter(article__pk=self.kwargs['pk'])
        for comment in comments:
            if comment.is_banned:
                comment.text = 'Комментарий заблокирован модератором'
        return comments

    def get_same_articles(self):

        category = self.object.category
        same_articles = self.model.objects.filter(
            category=category).annotate(cnt=Count('likes'))
        return same_articles.order_by('-cnt')[:5]


@method_decorator(csrf_exempt, name='dispatch')
class ArticleCreateView(LoginRequiredMixin, BanTestMixin, CreateView):
    model = Article
    template_name = 'mainapp/create_article.html'
    form_class = CreateArticleForm
    pk = None
    login_url = '/auth/login/'

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        self.object = article
        self.pk = article.pk
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('mainapp:article', kwargs={'pk': self.pk})


@method_decorator(csrf_exempt, name='dispatch')
class ArticleUpdateView(LoginRequiredMixin, AuthorTestMixin, UpdateView):
    model = Article
    template_name = 'mainapp/create_article.html'
    form_class = CreateArticleForm
    pk = None
    login_url = '/auth/login/'
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('mainapp:article', kwargs={'pk': self.pk})

    def form_valid(self, form):
        self.pk = self.object.pk
        return super(ArticleUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get('pk')
        content = super(ArticleUpdateView, self).get_context_data(**kwargs)
        content['title'] = 'Редактирование статьи'
        content['article'] = Article.objects.get(pk=pk)
        return content

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return Article.objects.get(pk=pk)


@method_decorator(csrf_exempt, name='dispatch')
class ArticleDeleteView(LoginRequiredMixin, AuthorTestMixin, DeleteView):
    model = Article
    login_url = '/auth/login/'
    success_url = reverse_lazy('mainapp:articles')

    def form_valid(self, form):
        self.object = self.get_object()
        if self.object.is_published:
            self.object.is_published = False
        else:
            self.object.is_published = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@method_decorator(csrf_exempt, name='dispatch')
class ArticlePublishView(LoginRequiredMixin, AuthorTestMixin, UpdateView):
    model = Article
    login_url = '/auth/login/'
    success_url = reverse_lazy('mainapp:articles')

    def form_valid(self, form):
        self.object = self.get_object()
        self.object.is_published = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


def about_us(request):
    title = 'о нас'
    content = {'title': title}

    return render(request, 'mainapp/about_us.html', content)


@method_decorator(csrf_exempt, name='dispatch')
class CommentView(LoginRequiredMixin, BanTestMixin, View):
    login_url = '/auth/login/'
    permission_denied_message = 'вы не авторизованны'

    def post(self, request, pk, *args, **kwargs):
        form = CommentForm(request.POST)
        article = Article.objects.get(pk=pk)

        if form.is_valid():
            text = form.cleaned_data['text']
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.article = article
            new_comment.save()

            comments = Comment.objects.filter(
                article=article).order_by('-created_at')
            context = {
                'article': article,
                'form': form,
                'comments': comments,
            }
            if '@moderator' in text:
                report = Report.create(object_pk=article, user=request.user)
                report.save()
        return HttpResponseRedirect(reverse('mainapp:article', kwargs={'pk': article.pk}))


@method_decorator(csrf_exempt, name='dispatch')
class CommentReplyView(LoginRequiredMixin, BanTestMixin, View):
    def post(self, request, article_pk, pk, *args, **kwargs):
        article = Article.objects.get(pk=article_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.article = article
            new_comment.parent = parent_comment
            new_comment.save()
            if '@moderator' in text:
                report = Report.create(
                    object_pk=parent_comment, user=request.user)
                report.save()

        comments = Comment.objects.filter(
            article=article).order_by('-created_at')
        context = {
            'article': article,
            'form': form,
            'comments': comments,
        }
        return HttpResponseRedirect(reverse('mainapp:article', kwargs={'pk': article_pk}))


@method_decorator(csrf_exempt, name='dispatch')
class LikeSwitcher(LoginRequiredMixin, BanTestMixin, View):
    login_url = '/auth/login/'
    permission_denied_message = 'вы не авторизованны'

    def handle_no_permission(self):
        self.request.path = self.request.META['HTTP_REFERER'].replace(
            self.request.META['HTTP_ORIGIN'], '')
        if self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            try:

                _handle_no_permission = super(
                    LikeSwitcher, self).handle_no_permission()
                if _handle_no_permission.status_code == 302:
                    return JsonResponse({'url': _handle_no_permission.url}, status=302)
            except PermissionDenied:
                return JsonResponse({"error": self.permission_denied_message}, status=403)
        return super(LikeSwitcher, self).handle_no_permission()

    def post(self, request, model, pk, *args, **kwargs):
        models = {
            Article.__name__: Article,
            Comment.__name__: Comment,
            User.__name__: User,
        }
        is_liked = False
        model_to_liked = models[model].objects.get(pk=pk)
        for like in model_to_liked.likes.all():
            if like == request.user:
                is_liked = True
                break
        if is_liked:
            model_to_liked.likes.remove(request.user)
        else:
            model_to_liked.likes.add(request.user)
        next = request.POST.get('next', '/')
        if self.request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            return JsonResponse({"likes_count": model_to_liked.likes.count()}, status=200)

        else:
            return HttpResponseRedirect(next)


def help(request):
    title = 'Помощь'
    content = {'title': title}

    return render(request, 'mainapp/help.html', content)

command_project/mainapp/templates/mainapp/about_us.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} О нас {% endblock %}
{% block content %}
<section class="u-clearfix u-section-1" id="sec-df54">
    <div class="u-clearfix u-sheet u-sheet-1"></div>
</section>

<section class="u-align-center u-clearfix u-section-2" id="sec-a4ee">
    <div class="u-clearfix u-sheet u-sheet-1">
        <img src="{% static 'images/mountain.jpeg' %}" alt="GOD SAVE US" width="800" height="300"/>
        <h2>Добро пожаловать</h2>
        <p>Русскоязычный веб-сайт в формате системы тематических коллективных блогов с элементами новостного сайта,
            созданный для публикации новостей, аналитических статей, мыслей, связанных с информационными технологиями,
            бизнесом и интернетом</p>
    </div>
</section>
{% endblock %}

command_project/mainapp/templates/mainapp/article.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} Статья {% endblock %}
{% block content %}

<div class="container my-5 py-5">

  <div class="row d-flex justify-content-center">
    <div class="card px-3 pt-3" style="max-width: 60rem">
      <!-- Статья -->
      <div>
        <!-- Фото -->
        <div class="bg-image hover-overlay shadow-1-strong ripple rounded-5 mb-4" data-mdb-ripple-color="light"><img
            src="{% if article.image %} {{ article.image.url }} {% else %} https://mdbcdn.b-cdn.net/img/new/slides/080.webp {% endif %}"
            alt="Article Image" class="img-fluid" width="900>
          <a href=" #!">
          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
          </a>
        </div>

        <!-- Данные о статье -->
        <div class="row mb-3">
          <div class="col-4 text-start">
            {{article.category}}
          </div>

          <div class="col-4 text-center">
            <a href="{% url 'auth:users_detail' article.author_id %}" class="text-info">
              <u> {{ article.author }}</u>
            </a>
          </div>

          <div class="col-4 text-end">
            <u> {{ article.created_date }}</u>
          </div>
        </div>

        <!-- Заголовок и текст -->
        <br>
        <div class="text-dark u-align-center">
          <h5>{{article.title}}</h5>
        </div>

        <p class="ms-4 fs-5 lh-lg u-body text-muted d-block">
          {{ article.article_text}}
        </p>

      </div>
      <div class="card-body">
        <div class="d-flex justify-content-between ">
        </div>
      </div>
      <!-- Реакции -->
      <div class="card-body">
        <div class="d-flex justify-content-between ">

          <div>
            <p class="text-muted">{{ comments.all.count }} комментариев </p>
          </div>
          <div>
            <div>
              {# {% if request.user.is_authenticated %}#}
              {% include "mainapp/includes/like.html" with model=article text="лайк статье"%}
              {# {% endif %}#}
            </div>

            <div>
              {% if request.user.is_staff %}
              {% if not article.is_banned %}
              <form method="POST" action="{% url 'mod:ban' model='article' pk=article.pk %}">
                {% csrf_token %}
                <button class="btn btn-link btn-xs" type="submit" name="next" value="{{ request.path }}">
                  <i class="fas fa-ban text-muted"></i>
                </button>
              </form>
              {% endif %}
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!-- Реакции -->

    </div>
  </div>
</div>

{% include "mainapp/includes/comments.html" %}

{% include 'mainapp/includes/inc_carousel.html' %}

<!-- Nav buttons -->
<div class="u-clearfix u-section-1 ">
  <a href="/" data-page-id="752105316"
    class="u-border-2 u-border-black u-btn u-button-style u-hover-black btn-outline-dark u-btn-1">
    Вернуться назад</a>

  {% if request.user.is_authenticated %}
  {% if request.user.pk == article.author.pk %}
  {% if article.is_published %}
  <form method="post" action="{% url 'mainapp:delete_article' article.pk %}"
    onclick="return confirm('Вы действительно хотите снять с публикации эту статью?')"> {% csrf_token %}
    <button class="u-border-2 u-border-black u-btn u-button-style u-hover-black u-btn-2">Снять с
      публикации
    </button>
  </form>
  <form method="post" action="{% url 'mainapp:update_article' article.pk %}"
    onclick="return confirm('Вы действительно хотите редактировать эту статью?')"> {% csrf_token %}
    <button class="u-border-2 u-border-black u-btn u-button-style u-hover-black u-btn-2">Редактировать статью
    </button>
  </form>
  {% endif %}
  {% if not article.is_published %}
  <form method="post" action="{% url 'mainapp:delete_article' article.pk %}"
    onclick="return confirm('Вы хотите опубликовать эту статью?')"> {% csrf_token %}
    <button class="u-border-2 u-border-black u-btn u-button-style u-hover-black u-btn-2"> Опубликовать статью
    </button>
  </form>
  <form method="post" action="{% url 'mainapp:update_article' article.pk %}"
    onclick="return confirm('Вы действительно хотите редактировать эту статью?')"> {% csrf_token %}
    <button class="u-border-2 u-border-black u-btn u-button-style u-hover-black u-btn-2">Редактировать статью
    </button>
  </form>
  {% endif %}
  {% endif %}
  {% endif %}
</div>
<!-- Nav buttons -->

{% endblock %}

command_project/mainapp/templates/mainapp/article_confirm_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %} Удаление статьи {% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите снять с публикации статью "{{ object.title }}"?</p>
    <input type="submit" value="Снять с публикации">
</form>
{% endblock %}

command_project/mainapp/templates/mainapp/articles.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<!--Section: All articles-->
<div class="row gx-5" style="width:80%; margin-left:10%;">
    {% for article in articles %}
  <div class="col-md-6 mb-4">
    <div class="bg-image hover-overlay ripple shadow-2-strong rounded-5"
      data-mdb-ripple-color="light">
      <img src="{% if article.image %} {{ article.image.url }} {% else %} https://mdbcdn.b-cdn.net/img/new/slides/080.webp {% endif %}" alt="Article Image" class="img-fluid" width="850">
      <a href="#!">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
      </a>
    </div>
  </div>

  <div class="col-md-6 mb-4">
    <span class="badge bg-danger px-2 py-1 shadow-1-strong mb-3">{{ article.category }}</span>
      <span class="badge bg-secondary px-2 py-1 shadow-1-strong mb-3">{{ article.author }}</span>
    <h4><strong>{{ article.title }}</strong></h4>
    <p class="text-muted">
      {{ article.article_text|truncatewords:100 }}
    </p>
    <a class='btn btn-light' href="{% url 'mainapp:article' article.pk %}">Читать дальше ...</a>
  </div>
    {% endfor %}
 <!-- Pagination -->
    <div class="row">
        <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Предыдущая</a>
                </li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Следующая</a>
                </li>
                {% endif %}

            </ul>
        </nav>
    </div>
    <!-- /Pagination -->

</div>

{% endblock %}

command_project/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}

<html style="font-size: 16px;">
{% block head %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="​Lorem ipsum dolor sit amet">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>{% block title %} Главная {% endblock %}</title>
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/comments.js' %}" defer=""></script>
    <!--    <link rel="stylesheet" href="{% static '/css/index.css' %}" media="screen">-->
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link id="u-theme-google-font" rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
{% endblock %}
<body class="u-body u-stick-footer">
{% block header %}
    {% include 'mainapp/includes/inc_header.html' %}
{% endblock %}
{% block categories %}
    {% include 'mainapp/includes/inc_categories.html' %}
{% endblock %}
<div>
    {% block content %}

    {% endblock %}
</div>


</body>
{% block footer %}
    {% include 'mainapp/includes/inc_footer.html' %}
{% endblock %}
</html>

command_project/mainapp/templates/mainapp/create_article.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<section class="u-clearfix u-section-1" id="sec-d509">
    <div class="u-clearfix u-sheet u-sheet-1">
        <a href="/" data-page-id="752105316"
           class="u-border-2 u-border-black u-btn u-button-style u-hover-black u-none u-text-black u-text-hover-white u-btn-1">Вернуться
            назад</a>
    </div>
</section>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card col-lg-6 offset-lg-3 mb-3">
        {% for field in form %}

        <div class="card-body">
            <label class="form-label">{{field.label}}</label>
            {{field}}
        </div>
        {% endfor %}

    </div>

    <div class="card col-lg-6 offset-lg-3 mb-3">
        <input type='submit' value="Отправить"/>
    </div>
</form>


{% endblock %}